#!/bin/bash

DTDANALYZER_HOME="$( dirname "${BASH_SOURCE[0]}" )"
CP="$DTDANALYZER_HOME/build"
SEP=':'
if [ $(uname -s | grep -ic 'cygwin\|mingw') -gt 0 ]; then SEP=';'; fi
for jar in "$DTDANALYZER_HOME"/lib/*.jar "$DTDANALYZER_HOME"/lib/*/*.jar
do
  CP="$CP$SEP$jar"
done
LOGCONFIG=${LOGCONFIG:-file:$DTDANALYZER_HOME/etc/log4j.properties}
exec java -cp "$CP" -Xmx256M "-Dlog4j.configuration=${LOGCONFIG}" \
           "-DDTDANALYZER_HOME=$DTDANALYZER_HOME" \
           gov.ncbi.pmc.dtdanalyzer.DtdAnalyzer "$@"
