#!/bin/bash

DTDANALYZER_ROOT="$( dirname "${BASH_SOURCE[0]}" )"
CP="$DTDANALYZER_ROOT/build"
SEP=':'
if [ $(uname -s | grep -ic 'cygwin\|mingw') -gt 0 ]; then SEP=';'; fi
for jar in "$DTDANALYZER_ROOT"/lib/*.jar "$DTDANALYZER_ROOT"/lib/*/*.jar
do
  CP="$CP$SEP$jar"
done
LOGCONFIG=${LOGCONFIG:-file:$DTDANALYZER_ROOT/etc/log4j.properties}
exec java -cp "$CP" -Xmx256M "-Dlog4j.configuration=${LOGCONFIG}" \
     gov.ncbi.pmc.dtdanalyzer.DtdDocumentor "$@"
